import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../core/services/app_services.dart';
import '../../core/utils/app_utils.dart';
import 'auth_provider.dart';

class SetupScreen extends ConsumerStatefulWidget{const SetupScreen({super.key});@override ConsumerState<SetupScreen> createState()=>_State();}
class _State extends ConsumerState<SetupScreen>{final form=GlobalKey<FormState>();final owner=TextEditingController(),business=TextEditingController(),phone=TextEditingController(),location=TextEditingController(text:'Makola'),pin=TextEditingController(),confirm=TextEditingController();bool saving=false;
  Future<void> save() async {if(!form.currentState!.validate())return;if(pin.text!=confirm.text){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('PINs do not match')));return;}setState(()=>saving=true);await ref.read(authProvider.notifier).setup(BusinessProfile(owner:owner.text.trim(),business:business.text.trim(),phone:phone.text.trim(),location:location.text.trim()),pin.text);}
  @override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:Form(key:form,child:ListView(padding:const EdgeInsets.all(24),children:[const Icon(Icons.storefront,size:70),const SizedBox(height:16),Text('Set up your shop',style:Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.w900)),const SizedBox(height:22),for(final entry in [(owner,'Owner name'),(business,'Business name'),(phone,'Phone number'),(location,'Market/location')])...[TextFormField(controller:entry.$1,decoration:InputDecoration(labelText:entry.$2),validator:(v)=>Validators.requiredText(v,label:entry.$2)),const SizedBox(height:12)],TextFormField(controller:pin,maxLength:4,obscureText:true,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Create 4-digit PIN',counterText:''),validator:Validators.pin),const SizedBox(height:12),TextFormField(controller:confirm,maxLength:4,obscureText:true,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Confirm PIN',counterText:''),validator:Validators.pin),const SizedBox(height:20),ElevatedButton(onPressed:saving?null:save,child:Text(saving?'Saving…':'Create shop'))]))));}
