import 'package:drift/drift.dart';

class Products extends Table {
  TextColumn get id=>text()(); TextColumn get name=>text()(); TextColumn get category=>text().withDefault(const Constant('General'))(); TextColumn get unit=>text().withDefault(const Constant('Piece'))(); RealColumn get costPrice=>real()(); RealColumn get sellingPrice=>real()(); IntColumn get quantity=>integer()(); IntColumn get lowStockThreshold=>integer().withDefault(const Constant(5))(); DateTimeColumn get createdAt=>dateTime()(); DateTimeColumn get updatedAt=>dateTime()(); @override Set<Column<Object>> get primaryKey=>{id};
}
class Customers extends Table {TextColumn get id=>text()();TextColumn get name=>text()();TextColumn get phone=>text().nullable()();TextColumn get location=>text().nullable()();DateTimeColumn get createdAt=>dateTime()();@override Set<Column<Object>> get primaryKey=>{id};}
class Sales extends Table {TextColumn get id=>text()();TextColumn get customerId=>text().nullable()();RealColumn get totalAmount=>real()();RealColumn get totalCost=>real()();RealColumn get amountPaid=>real()();TextColumn get paymentMethod=>text()();TextColumn get momoNetwork=>text().nullable()();TextColumn get momoReference=>text().nullable()();DateTimeColumn get createdAt=>dateTime()();@override Set<Column<Object>> get primaryKey=>{id};}
class SaleItems extends Table {TextColumn get id=>text()();TextColumn get saleId=>text()();TextColumn get productId=>text()();TextColumn get productName=>text()();IntColumn get quantity=>integer()();RealColumn get unitPrice=>real()();RealColumn get unitCost=>real()();@override Set<Column<Object>> get primaryKey=>{id};}
class Debts extends Table {TextColumn get id=>text()();TextColumn get customerId=>text()();TextColumn get saleId=>text().nullable()();RealColumn get originalAmount=>real()();RealColumn get balance=>real()();TextColumn get status=>text().withDefault(const Constant('open'))();DateTimeColumn get createdAt=>dateTime()();@override Set<Column<Object>> get primaryKey=>{id};}
class DebtPayments extends Table {TextColumn get id=>text()();TextColumn get debtId=>text()();RealColumn get amount=>real()();TextColumn get paymentMethod=>text()();DateTimeColumn get createdAt=>dateTime()();@override Set<Column<Object>> get primaryKey=>{id};}
class Expenses extends Table {TextColumn get id=>text()();TextColumn get category=>text()();TextColumn get description=>text()();RealColumn get amount=>real()();TextColumn get paymentMethod=>text()();DateTimeColumn get createdAt=>dateTime()();@override Set<Column<Object>> get primaryKey=>{id};}
