import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../core/database/app_database.dart';
import '../../core/utils/app_utils.dart';
import '../data/app_repository.dart';

class InventoryScreen extends ConsumerWidget{const InventoryScreen({super.key});Future<void> add(BuildContext context,WidgetRef ref)async{final f=GlobalKey<FormState>(),name=TextEditingController(),cat=TextEditingController(text:'General'),cost=TextEditingController(),sell=TextEditingController(),qty=TextEditingController(),low=TextEditingController(text:'5');String unit='Piece';final ok=await showModalBottomSheet<bool>(context:context,isScrollControlled:true,builder:(c)=>StatefulBuilder(builder:(c,set)=>Padding(padding:EdgeInsets.fromLTRB(16,18,16,MediaQuery.viewInsetsOf(c).bottom+20),child:Form(key:f,child:ListView(shrinkWrap:true,children:[Text('Add product',style:Theme.of(c).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w900)),const SizedBox(height:12),TextFormField(controller:name,decoration:const InputDecoration(labelText:'Product name'),validator:(v)=>Validators.requiredText(v,label:'Product name')),const SizedBox(height:10),TextFormField(controller:cat,decoration:const InputDecoration(labelText:'Category')),const SizedBox(height:10),DropdownButtonFormField(value:unit,decoration:const InputDecoration(labelText:'Unit'),items:['Piece','Pack','Box','Bottle','Bag','Kilogram'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>set(()=>unit=v!)),const SizedBox(height:10),TextFormField(controller:cost,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Cost price'),validator:Validators.money),const SizedBox(height:10),TextFormField(controller:sell,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Selling price'),validator:Validators.money),const SizedBox(height:10),TextFormField(controller:qty,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Opening quantity'),validator:Validators.whole),const SizedBox(height:10),TextFormField(controller:low,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Low-stock level'),validator:Validators.whole),const SizedBox(height:16),ElevatedButton(onPressed:(){if(f.currentState!.validate())Navigator.pop(c,true);},child:const Text('Save product'))])))));if(ok==true)await ref.read(repoProvider).addProduct(name.text.trim(),cat.text.trim(),unit,double.parse(cost.text),double.parse(sell.text),int.parse(qty.text),int.parse(low.text));}
Future<void> adjust(BuildContext context,WidgetRef ref,Product p)async{final c=TextEditingController(text:p.quantity.toString());final q=await showDialog<int>(context:context,builder:(x)=>AlertDialog(title:Text('Adjust ${p.name}'),content:TextField(controller:c,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'New quantity')),actions:[TextButton(onPressed:()=>Navigator.pop(x),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(x,int.tryParse(c.text)),child:const Text('Save'))]));if(q!=null)await ref.read(repoProvider).adjust(p,q);}
@override Widget build(BuildContext context,WidgetRef ref){final a=ref.watch(productsProvider);return Scaffold(appBar:AppBar(title:const Text('Inventory')),body:a.when(loading:()=>const Center(child:CircularProgressIndicator()),error:(e,_)=>Center(child:Text('$e')),data:(items)=>items.isEmpty?const Center(child:Text('No products yet')):ListView.separated(padding:const EdgeInsets.fromLTRB(16,8,16,100),itemCount:items.length,separatorBuilder:(_,__)=>const SizedBox(height:10),itemBuilder:(_,i){final p=items[i],low=p.quantity<=p.lowStockThreshold;return Card(child:ListTile(contentPadding:const EdgeInsets.all(14),leading:CircleAvatar(child:Icon(low?Icons.warning_amber:Icons.inventory_2_outlined)),title:Text(p.name,style:const TextStyle(fontWeight:FontWeight.w900)),subtitle:Text('${p.category} · ${formatGhs(p.sellingPrice)} / ${p.unit}'),trailing:Text('${p.quantity}',style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900)),onTap:()=>adjust(context,ref,p)));})),floatingActionButton:FloatingActionButton.extended(onPressed:()=>add(context,ref),icon:const Icon(Icons.add),label:const Text('Add product')));}}
